//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopping.Models
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.AccountGroups = new HashSet<AccountGroup>();
        }
        [Required]
        [Display(Name = "ID Người Dùng")]
        public int id { get; set; }
        [Required]
        [Display(Name ="Tên Người Dùng")]
        public string accountName { get; set; }
        [Required]
        [Display(Name = "Mật Khẩu Người Dùng")]
        public string password { get; set; }
        [Required]
        [Display(Name = "Tên Đầy Đủ")]
        public string fullName { get; set; }
        public string imagePath { get; set; }
        [Required]
        [Display(Name = "Ngày Sinh")]
        public Nullable<System.DateTime> birthDay { get; set; }
        [Required]
        [Display(Name = "Số Điện Thoại")]
        public string phone { get; set; }
        [Required]
        [Display(Name = "Địa Chỉ Email")]
        public string email { get; set; }
        [Required]
        [Display(Name = "Địa Chỉ Nhà")]
        public string address { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        [Required]
        [Display(Name = "Thuộc Nhóm Người Dùng")]
        public Nullable<int> groupId { get; set; }
        [Required]
        [Display(Name = "Trạng Thái Tài Khoản")]
        public Nullable<int> active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountGroup> AccountGroups { get; set; }
    }
}
