//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopping.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AccountGroup
    {
        public int id { get; set; }
        public Nullable<int> groupId { get; set; }
        [Required]
        [Display(Name = "ID Người Dùng")]
        public Nullable<int> accountId { get; set; }
        [Required]
        [Display(Name = "Trạng Thái Nhóm")]
        public Nullable<int> active { get; set; }
    
        public virtual Account Account { get; set; }
        [Required]
        [Display(Name = "Tên Nhóm")]
        public virtual Group Group { get; set; }
    }
}
