//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public Author()
        {
            this.Books = new HashSet<Book>();
        }
    
        public int author_Id { get; set; }
        public string author_Name { get; set; }
        public string author_Address { get; set; }
        public string author_Story { get; set; }
    
        public virtual ICollection<Book> Books { get; set; }
    }
}
