//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopping.Models
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int customer_Id { get; set; }
        [Required]
        public string customer_Fullname { get; set; }
        public string customer_Address { get; set; }
        public string customer_Phone { get; set; }
        public string customer_Email { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
