//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopping.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int customer_Id { get; set; }
        [Required]
        [Display(Name = "Tên Khách Hàng")]
        public string customer_Fullname { get; set; }
        [Required]
        [Display(Name = "Địa Chỉ")]
        public string customer_Address { get; set; }
        [Required]
        [Display(Name = "Số Điện Thoại")]
        public string customer_Phone { get; set; }
        [Required]
        [Display(Name = "Email")]
        public string customer_Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
