//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderdetail
    {
        public int orderdetail_Id { get; set; }
        public Nullable<int> orderdetail_book_Id { get; set; }
        public Nullable<int> orderdetail_Quantity { get; set; }
        public Nullable<int> orderdetail_Price { get; set; }
        public Nullable<int> orderdetail_Total { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Order Order { get; set; }
    }
}
