//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopping.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Path
    {
        public Path()
        {
            this.GroupPaths = new HashSet<GroupPath>();
        }
    
        public int id { get; set; }
        [Required]
        [Display(Name = "Tên Chưc Năng")]
        public string pathName { get; set; }
        [Required]
        [Display(Name = "Mô Tả Chức Năng")]
        public string pathDescription { get; set; }
        [Required]
        [Display(Name = "Đường Dẫn Chức Năng")]
        public string pathUrl { get; set; }
        public string imageUrl { get; set; }
        public Nullable<int> display { get; set; }
        [Required]
        [Display(Name = "Đường Dẫn Cha")]
        public Nullable<int> parentId { get; set; }
        [Required]
        [Display(Name = "Trạng Thái")]
        public Nullable<int> active { get; set; }
    
        public virtual ICollection<GroupPath> GroupPaths { get; set; }
    }
}
