//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopping.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Publisher
    {
        public Publisher()
        {
            this.Books = new HashSet<Book>();
        }
        [Required]
        [Display(Name = "Nhà Xuất Bản")]
        public int publisher_Id { get; set; }
        [Required]
        [Display(Name = "Nhà Xuất Bản")]
        public string publisher_Name { get; set; }
        public string publisher_Slug { get; set; }
    
        public virtual ICollection<Book> Books { get; set; }
    }
}
