//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sub_Category
    {
        public int subcategory_Id { get; set; }
        public string subcategory_Name { get; set; }
        public Nullable<int> parent_CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
